title: New Koahla Physics Sims
color_scheme: dark

# Enable Jekyll Collections
collections:
  simulations:
    output: true
    permalink: /:collection/:path/
  lessons:
    output: true
    permalink: /:collection/:path/

# Configure Just the Docs Dropdown Menus
just_the_docs:
  collections:
    simulations:
      name: Simulations
      nav_fold: true
    lessons:
      name: Lessons
      nav_fold: true
